### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Zibri** [ScaleDrone/webrtc#4]
DOMException: Failed to set local answer sdp: Called in wrong state: kStable

**Comment by CybrZr00** [comment]
I also get this error, to expand on it a bit, the error is happening here (looks a bit different from standard as I use my own signalr server for signaling:

`    connection.on('newMessage', (message) => {
        message = JSON.parse(message);
        if (message.sdp) {
            // This is called after receiving an offer or answer from another peer
            pc.setRemoteDescription(new RTCSessionDescription(message.sdp), () => {
                // When receiving an offer lets answer it
                if (pc.remoteDescription.type === 'offer') {
                    pc.createAnswer().then(localDescCreated).catch(error => onError("createAnswer", error));
                }
            }, error => onError("setRemoteDescription", error));
        } else if (message.candidate) {
            // Add the new ICE candidate to our connections remote description
            pc.addIceCandidate(
                new RTCIceCandidate(message.candidate), onSuccess, error => onError("addIceCandidate", error)
            );
        }
    });`

I then get an error about this:

`function localDescCreated(desc) {
    pc.setLocalDescription(
        desc,
        () => sendMessage(JSON.stringify({ 'sdp': pc.localDescription })),
        error => onError("func localDescCreated", error)
    );
}`  

I have customised the error handler (in addition to signaling) to give me context which is why it looks a little different.

I've googled and looked around, but can't for the life of me figure this out.

**Comment by herkyl** [comment]
Which browser/OS are you getting this on? Does it happen on other browsers?

**Comment by CybrZr00** [comment]
I am using windows.

I found it happens regardless of browser, however I have added a turn server as well as a stun server and that seems to have it working... as long as I stay away from Microsoft's browsers :D

The error's do still show in the console, but since it works I assume it's because not all connections tried work, again assuming the scripts cycle through the stun servers offerings.

**Comment by herkyl** [comment]
@CybrZr00 do you mind sharing the code for adding the TURN server? Did you set the TURN server up yourself?

**Comment by CybrZr00** [comment]
@herkyl I just used the free numb servers:

`const configuration = {
    iceServers: [
        {
            urls: ["turn:numb.viagenie.ca:3478","stun:numb.viagenie.ca:3478"],
            username: "REMOVED",
            credential: "REMOVED"
        }
    ]
};`

with: 
`pc = new RTCPeerConnection(configuration);`

**Comment by herkyl** [comment]
Thanks @CybrZr00 🎉 !

I'm going to close the issue. If anyone runs into this there is a fix here now, it simply doesn't fit into the tutorial
